//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiceIntegration.wsRsaSendOsago {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ISend_OSAGO_Servicebinding", Namespace="http://tempuri.org/")]
    public partial class ISend_OSAGO_Serviceservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Send_OSAGO_24OperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_OSAGO_Get_Reject_NumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_OSAGO_RejectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_EOSAGO_2_ASOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_TO_24OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ISend_OSAGO_Serviceservice() {
            this.Url = global::ServiceIntegration.Properties.Settings.Default.ServiceIntegration_wsRsaSendOsago_ISend_OSAGO_Serviceservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Send_OSAGO_24CompletedEventHandler Send_OSAGO_24Completed;
        
        /// <remarks/>
        public event Send_OSAGO_Get_Reject_NumberCompletedEventHandler Send_OSAGO_Get_Reject_NumberCompleted;
        
        /// <remarks/>
        public event Send_OSAGO_RejectCompletedEventHandler Send_OSAGO_RejectCompleted;
        
        /// <remarks/>
        public event Send_EOSAGO_2_ASCompletedEventHandler Send_EOSAGO_2_ASCompleted;
        
        /// <remarks/>
        public event Send_TO_24CompletedEventHandler Send_TO_24Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service#Send_OSAGO_24", RequestNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service", ResponseNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Send_OSAGO_24(string XML_Node_Data, string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name, bool Check_Only_Dont_Send, string VersionsSL, string Agent_IP) {
            object[] results = this.Invoke("Send_OSAGO_24", new object[] {
                        XML_Node_Data,
                        Partner_System_Name,
                        Branch_Code,
                        Agent_LNR,
                        Agent_name,
                        Check_Only_Dont_Send,
                        VersionsSL,
                        Agent_IP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_OSAGO_24Async(string XML_Node_Data, string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name, bool Check_Only_Dont_Send, string VersionsSL, string Agent_IP) {
            this.Send_OSAGO_24Async(XML_Node_Data, Partner_System_Name, Branch_Code, Agent_LNR, Agent_name, Check_Only_Dont_Send, VersionsSL, Agent_IP, null);
        }
        
        /// <remarks/>
        public void Send_OSAGO_24Async(string XML_Node_Data, string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name, bool Check_Only_Dont_Send, string VersionsSL, string Agent_IP, object userState) {
            if ((this.Send_OSAGO_24OperationCompleted == null)) {
                this.Send_OSAGO_24OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_OSAGO_24OperationCompleted);
            }
            this.InvokeAsync("Send_OSAGO_24", new object[] {
                        XML_Node_Data,
                        Partner_System_Name,
                        Branch_Code,
                        Agent_LNR,
                        Agent_name,
                        Check_Only_Dont_Send,
                        VersionsSL,
                        Agent_IP}, this.Send_OSAGO_24OperationCompleted, userState);
        }
        
        private void OnSend_OSAGO_24OperationCompleted(object arg) {
            if ((this.Send_OSAGO_24Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_OSAGO_24Completed(this, new Send_OSAGO_24CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service#Send_OSAGO_Get_Reject_Number", RequestNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service", ResponseNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Send_OSAGO_Get_Reject_Number(string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name, string XML_Node_Data) {
            object[] results = this.Invoke("Send_OSAGO_Get_Reject_Number", new object[] {
                        Partner_System_Name,
                        Branch_Code,
                        Agent_LNR,
                        Agent_name,
                        XML_Node_Data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_OSAGO_Get_Reject_NumberAsync(string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name, string XML_Node_Data) {
            this.Send_OSAGO_Get_Reject_NumberAsync(Partner_System_Name, Branch_Code, Agent_LNR, Agent_name, XML_Node_Data, null);
        }
        
        /// <remarks/>
        public void Send_OSAGO_Get_Reject_NumberAsync(string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name, string XML_Node_Data, object userState) {
            if ((this.Send_OSAGO_Get_Reject_NumberOperationCompleted == null)) {
                this.Send_OSAGO_Get_Reject_NumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_OSAGO_Get_Reject_NumberOperationCompleted);
            }
            this.InvokeAsync("Send_OSAGO_Get_Reject_Number", new object[] {
                        Partner_System_Name,
                        Branch_Code,
                        Agent_LNR,
                        Agent_name,
                        XML_Node_Data}, this.Send_OSAGO_Get_Reject_NumberOperationCompleted, userState);
        }
        
        private void OnSend_OSAGO_Get_Reject_NumberOperationCompleted(object arg) {
            if ((this.Send_OSAGO_Get_Reject_NumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_OSAGO_Get_Reject_NumberCompleted(this, new Send_OSAGO_Get_Reject_NumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service#Send_OSAGO_Reject", RequestNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service", ResponseNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Send_OSAGO_Reject(string XML_Node_Data, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] PDF_FileBody, string Partner_System_Name) {
            object[] results = this.Invoke("Send_OSAGO_Reject", new object[] {
                        XML_Node_Data,
                        PDF_FileBody,
                        Partner_System_Name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_OSAGO_RejectAsync(string XML_Node_Data, byte[] PDF_FileBody, string Partner_System_Name) {
            this.Send_OSAGO_RejectAsync(XML_Node_Data, PDF_FileBody, Partner_System_Name, null);
        }
        
        /// <remarks/>
        public void Send_OSAGO_RejectAsync(string XML_Node_Data, byte[] PDF_FileBody, string Partner_System_Name, object userState) {
            if ((this.Send_OSAGO_RejectOperationCompleted == null)) {
                this.Send_OSAGO_RejectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_OSAGO_RejectOperationCompleted);
            }
            this.InvokeAsync("Send_OSAGO_Reject", new object[] {
                        XML_Node_Data,
                        PDF_FileBody,
                        Partner_System_Name}, this.Send_OSAGO_RejectOperationCompleted, userState);
        }
        
        private void OnSend_OSAGO_RejectOperationCompleted(object arg) {
            if ((this.Send_OSAGO_RejectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_OSAGO_RejectCompleted(this, new Send_OSAGO_RejectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service#Send_EOSAGO_2_AS", RequestNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service", ResponseNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Send_EOSAGO_2_AS(string DraftPolicyID, string Region, string policy_series, string policy_number) {
            object[] results = this.Invoke("Send_EOSAGO_2_AS", new object[] {
                        DraftPolicyID,
                        Region,
                        policy_series,
                        policy_number});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_EOSAGO_2_ASAsync(string DraftPolicyID, string Region, string policy_series, string policy_number) {
            this.Send_EOSAGO_2_ASAsync(DraftPolicyID, Region, policy_series, policy_number, null);
        }
        
        /// <remarks/>
        public void Send_EOSAGO_2_ASAsync(string DraftPolicyID, string Region, string policy_series, string policy_number, object userState) {
            if ((this.Send_EOSAGO_2_ASOperationCompleted == null)) {
                this.Send_EOSAGO_2_ASOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_EOSAGO_2_ASOperationCompleted);
            }
            this.InvokeAsync("Send_EOSAGO_2_AS", new object[] {
                        DraftPolicyID,
                        Region,
                        policy_series,
                        policy_number}, this.Send_EOSAGO_2_ASOperationCompleted, userState);
        }
        
        private void OnSend_EOSAGO_2_ASOperationCompleted(object arg) {
            if ((this.Send_EOSAGO_2_ASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_EOSAGO_2_ASCompleted(this, new Send_EOSAGO_2_ASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service#Send_TO_24", RequestNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service", ResponseNamespace="urn:Send_OSAGO_Service_srv-ISend_OSAGO_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Send_TO_24(string XML_Node_Data, string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name) {
            object[] results = this.Invoke("Send_TO_24", new object[] {
                        XML_Node_Data,
                        Partner_System_Name,
                        Branch_Code,
                        Agent_LNR,
                        Agent_name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_TO_24Async(string XML_Node_Data, string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name) {
            this.Send_TO_24Async(XML_Node_Data, Partner_System_Name, Branch_Code, Agent_LNR, Agent_name, null);
        }
        
        /// <remarks/>
        public void Send_TO_24Async(string XML_Node_Data, string Partner_System_Name, string Branch_Code, string Agent_LNR, string Agent_name, object userState) {
            if ((this.Send_TO_24OperationCompleted == null)) {
                this.Send_TO_24OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_TO_24OperationCompleted);
            }
            this.InvokeAsync("Send_TO_24", new object[] {
                        XML_Node_Data,
                        Partner_System_Name,
                        Branch_Code,
                        Agent_LNR,
                        Agent_name}, this.Send_TO_24OperationCompleted, userState);
        }
        
        private void OnSend_TO_24OperationCompleted(object arg) {
            if ((this.Send_TO_24Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_TO_24Completed(this, new Send_TO_24CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Send_OSAGO_24CompletedEventHandler(object sender, Send_OSAGO_24CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_OSAGO_24CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_OSAGO_24CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Send_OSAGO_Get_Reject_NumberCompletedEventHandler(object sender, Send_OSAGO_Get_Reject_NumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_OSAGO_Get_Reject_NumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_OSAGO_Get_Reject_NumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Send_OSAGO_RejectCompletedEventHandler(object sender, Send_OSAGO_RejectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_OSAGO_RejectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_OSAGO_RejectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Send_EOSAGO_2_ASCompletedEventHandler(object sender, Send_EOSAGO_2_ASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_EOSAGO_2_ASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_EOSAGO_2_ASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Send_TO_24CompletedEventHandler(object sender, Send_TO_24CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_TO_24CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_TO_24CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591