//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiceIntegration.wsArm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IAPO2_ARM_READERbinding", Namespace="http://tempuri.org/")]
    public partial class IAPO2_ARM_READERservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataA4OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKbmToOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoContractsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_BSOOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_BSO2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_BSO3OperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_BSO4OperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_BSO5OperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_BSO6OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFactDatabyAgentIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPreferentialExtensionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVPNUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Block_BSOOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteStatisticOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckOurNPFClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNPFAgentOperationCompleted;
        
        private System.Threading.SendOrPostCallback PassportIsBadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServerDateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback WritePolicyToMGDBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_APO2_Last_VersionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentsByLNR_INNOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmModifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsAllowedModifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteToSplunkOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteToSplunk2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IAPO2_ARM_READERservice() {
            this.Url = global::ServiceIntegration.Properties.Settings.Default.ServiceIntegration_wsArm_IAPO2_ARM_READERservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataA4CompletedEventHandler GetDataA4Completed;
        
        /// <remarks/>
        public event GetKbmToCompletedEventHandler GetKbmToCompleted;
        
        /// <remarks/>
        public event GetInfoContractsCompletedEventHandler GetInfoContractsCompleted;
        
        /// <remarks/>
        public event Check_BSOCompletedEventHandler Check_BSOCompleted;
        
        /// <remarks/>
        public event Check_BSO2CompletedEventHandler Check_BSO2Completed;
        
        /// <remarks/>
        public event Check_BSO3CompletedEventHandler Check_BSO3Completed;
        
        /// <remarks/>
        public event Check_BSO4CompletedEventHandler Check_BSO4Completed;
        
        /// <remarks/>
        public event Check_BSO5CompletedEventHandler Check_BSO5Completed;
        
        /// <remarks/>
        public event Check_BSO6CompletedEventHandler Check_BSO6Completed;
        
        /// <remarks/>
        public event GetFactDatabyAgentIDCompletedEventHandler GetFactDatabyAgentIDCompleted;
        
        /// <remarks/>
        public event CheckPreferentialExtensionCompletedEventHandler CheckPreferentialExtensionCompleted;
        
        /// <remarks/>
        public event GetVPNUserCompletedEventHandler GetVPNUserCompleted;
        
        /// <remarks/>
        public event Block_BSOCompletedEventHandler Block_BSOCompleted;
        
        /// <remarks/>
        public event WriteStatisticCompletedEventHandler WriteStatisticCompleted;
        
        /// <remarks/>
        public event CheckOurNPFClientCompletedEventHandler CheckOurNPFClientCompleted;
        
        /// <remarks/>
        public event GetNPFAgentCompletedEventHandler GetNPFAgentCompleted;
        
        /// <remarks/>
        public event PassportIsBadCompletedEventHandler PassportIsBadCompleted;
        
        /// <remarks/>
        public event GetServerDateTimeCompletedEventHandler GetServerDateTimeCompleted;
        
        /// <remarks/>
        public event WritePolicyToMGDBCompletedEventHandler WritePolicyToMGDBCompleted;
        
        /// <remarks/>
        public event Check_APO2_Last_VersionsCompletedEventHandler Check_APO2_Last_VersionsCompleted;
        
        /// <remarks/>
        public event GetAgentsByLNR_INNCompletedEventHandler GetAgentsByLNR_INNCompleted;
        
        /// <remarks/>
        public event ConfirmModifyCompletedEventHandler ConfirmModifyCompleted;
        
        /// <remarks/>
        public event IsAllowedModifyCompletedEventHandler IsAllowedModifyCompleted;
        
        /// <remarks/>
        public event WriteToSplunkCompletedEventHandler WriteToSplunkCompleted;
        
        /// <remarks/>
        public event WriteToSplunk2CompletedEventHandler WriteToSplunk2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetData", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetData(string XML) {
            object[] results = this.Invoke("GetData", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(string XML) {
            this.GetDataAsync(XML, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(string XML, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        XML}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetDataA4", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetDataA4(string policy_id, string actualDate) {
            object[] results = this.Invoke("GetDataA4", new object[] {
                        policy_id,
                        actualDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataA4Async(string policy_id, string actualDate) {
            this.GetDataA4Async(policy_id, actualDate, null);
        }
        
        /// <remarks/>
        public void GetDataA4Async(string policy_id, string actualDate, object userState) {
            if ((this.GetDataA4OperationCompleted == null)) {
                this.GetDataA4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataA4OperationCompleted);
            }
            this.InvokeAsync("GetDataA4", new object[] {
                        policy_id,
                        actualDate}, this.GetDataA4OperationCompleted, userState);
        }
        
        private void OnGetDataA4OperationCompleted(object arg) {
            if ((this.GetDataA4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataA4Completed(this, new GetDataA4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetKbmTo", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetKbmTo(string data, string CorrelationId) {
            object[] results = this.Invoke("GetKbmTo", new object[] {
                        data,
                        CorrelationId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetKbmToAsync(string data, string CorrelationId) {
            this.GetKbmToAsync(data, CorrelationId, null);
        }
        
        /// <remarks/>
        public void GetKbmToAsync(string data, string CorrelationId, object userState) {
            if ((this.GetKbmToOperationCompleted == null)) {
                this.GetKbmToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKbmToOperationCompleted);
            }
            this.InvokeAsync("GetKbmTo", new object[] {
                        data,
                        CorrelationId}, this.GetKbmToOperationCompleted, userState);
        }
        
        private void OnGetKbmToOperationCompleted(object arg) {
            if ((this.GetKbmToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKbmToCompleted(this, new GetKbmToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetInfoContracts", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetInfoContracts(string request_xml) {
            object[] results = this.Invoke("GetInfoContracts", new object[] {
                        request_xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoContractsAsync(string request_xml) {
            this.GetInfoContractsAsync(request_xml, null);
        }
        
        /// <remarks/>
        public void GetInfoContractsAsync(string request_xml, object userState) {
            if ((this.GetInfoContractsOperationCompleted == null)) {
                this.GetInfoContractsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoContractsOperationCompleted);
            }
            this.InvokeAsync("GetInfoContracts", new object[] {
                        request_xml}, this.GetInfoContractsOperationCompleted, userState);
        }
        
        private void OnGetInfoContractsOperationCompleted(object arg) {
            if ((this.GetInfoContractsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoContractsCompleted(this, new GetInfoContractsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Check_BSO", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int Check_BSO(string BSO_ser, string BSO_num, string ARM_Agent_ID) {
            object[] results = this.Invoke("Check_BSO", new object[] {
                        BSO_ser,
                        BSO_num,
                        ARM_Agent_ID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Check_BSOAsync(string BSO_ser, string BSO_num, string ARM_Agent_ID) {
            this.Check_BSOAsync(BSO_ser, BSO_num, ARM_Agent_ID, null);
        }
        
        /// <remarks/>
        public void Check_BSOAsync(string BSO_ser, string BSO_num, string ARM_Agent_ID, object userState) {
            if ((this.Check_BSOOperationCompleted == null)) {
                this.Check_BSOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_BSOOperationCompleted);
            }
            this.InvokeAsync("Check_BSO", new object[] {
                        BSO_ser,
                        BSO_num,
                        ARM_Agent_ID}, this.Check_BSOOperationCompleted, userState);
        }
        
        private void OnCheck_BSOOperationCompleted(object arg) {
            if ((this.Check_BSOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_BSOCompleted(this, new Check_BSOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Check_BSO2", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int Check_BSO2(string BSO_ser, string BSO_num, string ARM_Agent_ID, int bso_type_id) {
            object[] results = this.Invoke("Check_BSO2", new object[] {
                        BSO_ser,
                        BSO_num,
                        ARM_Agent_ID,
                        bso_type_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Check_BSO2Async(string BSO_ser, string BSO_num, string ARM_Agent_ID, int bso_type_id) {
            this.Check_BSO2Async(BSO_ser, BSO_num, ARM_Agent_ID, bso_type_id, null);
        }
        
        /// <remarks/>
        public void Check_BSO2Async(string BSO_ser, string BSO_num, string ARM_Agent_ID, int bso_type_id, object userState) {
            if ((this.Check_BSO2OperationCompleted == null)) {
                this.Check_BSO2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_BSO2OperationCompleted);
            }
            this.InvokeAsync("Check_BSO2", new object[] {
                        BSO_ser,
                        BSO_num,
                        ARM_Agent_ID,
                        bso_type_id}, this.Check_BSO2OperationCompleted, userState);
        }
        
        private void OnCheck_BSO2OperationCompleted(object arg) {
            if ((this.Check_BSO2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_BSO2Completed(this, new Check_BSO2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Check_BSO3", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int Check_BSO3(string BSO_ser, string BSO_num) {
            object[] results = this.Invoke("Check_BSO3", new object[] {
                        BSO_ser,
                        BSO_num});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Check_BSO3Async(string BSO_ser, string BSO_num) {
            this.Check_BSO3Async(BSO_ser, BSO_num, null);
        }
        
        /// <remarks/>
        public void Check_BSO3Async(string BSO_ser, string BSO_num, object userState) {
            if ((this.Check_BSO3OperationCompleted == null)) {
                this.Check_BSO3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_BSO3OperationCompleted);
            }
            this.InvokeAsync("Check_BSO3", new object[] {
                        BSO_ser,
                        BSO_num}, this.Check_BSO3OperationCompleted, userState);
        }
        
        private void OnCheck_BSO3OperationCompleted(object arg) {
            if ((this.Check_BSO3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_BSO3Completed(this, new Check_BSO3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Check_BSO4", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Check_BSO4(string BSO_ser, string BSO_num, int BSO_TypeID, string Agent_LNR, string Agent_SKK) {
            object[] results = this.Invoke("Check_BSO4", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID,
                        Agent_LNR,
                        Agent_SKK});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_BSO4Async(string BSO_ser, string BSO_num, int BSO_TypeID, string Agent_LNR, string Agent_SKK) {
            this.Check_BSO4Async(BSO_ser, BSO_num, BSO_TypeID, Agent_LNR, Agent_SKK, null);
        }
        
        /// <remarks/>
        public void Check_BSO4Async(string BSO_ser, string BSO_num, int BSO_TypeID, string Agent_LNR, string Agent_SKK, object userState) {
            if ((this.Check_BSO4OperationCompleted == null)) {
                this.Check_BSO4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_BSO4OperationCompleted);
            }
            this.InvokeAsync("Check_BSO4", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID,
                        Agent_LNR,
                        Agent_SKK}, this.Check_BSO4OperationCompleted, userState);
        }
        
        private void OnCheck_BSO4OperationCompleted(object arg) {
            if ((this.Check_BSO4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_BSO4Completed(this, new Check_BSO4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Check_BSO5", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Check_BSO5(string BSO_ser, string BSO_num, int BSO_TypeID, string Agent_LNR, string Agent_SKK, string Date_of_Issue) {
            object[] results = this.Invoke("Check_BSO5", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID,
                        Agent_LNR,
                        Agent_SKK,
                        Date_of_Issue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_BSO5Async(string BSO_ser, string BSO_num, int BSO_TypeID, string Agent_LNR, string Agent_SKK, string Date_of_Issue) {
            this.Check_BSO5Async(BSO_ser, BSO_num, BSO_TypeID, Agent_LNR, Agent_SKK, Date_of_Issue, null);
        }
        
        /// <remarks/>
        public void Check_BSO5Async(string BSO_ser, string BSO_num, int BSO_TypeID, string Agent_LNR, string Agent_SKK, string Date_of_Issue, object userState) {
            if ((this.Check_BSO5OperationCompleted == null)) {
                this.Check_BSO5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_BSO5OperationCompleted);
            }
            this.InvokeAsync("Check_BSO5", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID,
                        Agent_LNR,
                        Agent_SKK,
                        Date_of_Issue}, this.Check_BSO5OperationCompleted, userState);
        }
        
        private void OnCheck_BSO5OperationCompleted(object arg) {
            if ((this.Check_BSO5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_BSO5Completed(this, new Check_BSO5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Check_BSO6", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int Check_BSO6(string BSO_ser, string BSO_num, int BSO_TypeID) {
            object[] results = this.Invoke("Check_BSO6", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Check_BSO6Async(string BSO_ser, string BSO_num, int BSO_TypeID) {
            this.Check_BSO6Async(BSO_ser, BSO_num, BSO_TypeID, null);
        }
        
        /// <remarks/>
        public void Check_BSO6Async(string BSO_ser, string BSO_num, int BSO_TypeID, object userState) {
            if ((this.Check_BSO6OperationCompleted == null)) {
                this.Check_BSO6OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_BSO6OperationCompleted);
            }
            this.InvokeAsync("Check_BSO6", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID}, this.Check_BSO6OperationCompleted, userState);
        }
        
        private void OnCheck_BSO6OperationCompleted(object arg) {
            if ((this.Check_BSO6Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_BSO6Completed(this, new Check_BSO6CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetFactDatabyAgentID", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetFactDatabyAgentID(string AgentID, string dt) {
            object[] results = this.Invoke("GetFactDatabyAgentID", new object[] {
                        AgentID,
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFactDatabyAgentIDAsync(string AgentID, string dt) {
            this.GetFactDatabyAgentIDAsync(AgentID, dt, null);
        }
        
        /// <remarks/>
        public void GetFactDatabyAgentIDAsync(string AgentID, string dt, object userState) {
            if ((this.GetFactDatabyAgentIDOperationCompleted == null)) {
                this.GetFactDatabyAgentIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFactDatabyAgentIDOperationCompleted);
            }
            this.InvokeAsync("GetFactDatabyAgentID", new object[] {
                        AgentID,
                        dt}, this.GetFactDatabyAgentIDOperationCompleted, userState);
        }
        
        private void OnGetFactDatabyAgentIDOperationCompleted(object arg) {
            if ((this.GetFactDatabyAgentIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFactDatabyAgentIDCompleted(this, new GetFactDatabyAgentIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#CheckPreferentialExtension", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CheckPreferentialExtension(string request_xml) {
            object[] results = this.Invoke("CheckPreferentialExtension", new object[] {
                        request_xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPreferentialExtensionAsync(string request_xml) {
            this.CheckPreferentialExtensionAsync(request_xml, null);
        }
        
        /// <remarks/>
        public void CheckPreferentialExtensionAsync(string request_xml, object userState) {
            if ((this.CheckPreferentialExtensionOperationCompleted == null)) {
                this.CheckPreferentialExtensionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPreferentialExtensionOperationCompleted);
            }
            this.InvokeAsync("CheckPreferentialExtension", new object[] {
                        request_xml}, this.CheckPreferentialExtensionOperationCompleted, userState);
        }
        
        private void OnCheckPreferentialExtensionOperationCompleted(object arg) {
            if ((this.CheckPreferentialExtensionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPreferentialExtensionCompleted(this, new CheckPreferentialExtensionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetVPNUser", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetVPNUser(string ClientIP) {
            object[] results = this.Invoke("GetVPNUser", new object[] {
                        ClientIP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVPNUserAsync(string ClientIP) {
            this.GetVPNUserAsync(ClientIP, null);
        }
        
        /// <remarks/>
        public void GetVPNUserAsync(string ClientIP, object userState) {
            if ((this.GetVPNUserOperationCompleted == null)) {
                this.GetVPNUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVPNUserOperationCompleted);
            }
            this.InvokeAsync("GetVPNUser", new object[] {
                        ClientIP}, this.GetVPNUserOperationCompleted, userState);
        }
        
        private void OnGetVPNUserOperationCompleted(object arg) {
            if ((this.GetVPNUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVPNUserCompleted(this, new GetVPNUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Block_BSO", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Block_BSO(string BSO_ser, string BSO_num, int BSO_TypeID) {
            object[] results = this.Invoke("Block_BSO", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Block_BSOAsync(string BSO_ser, string BSO_num, int BSO_TypeID) {
            this.Block_BSOAsync(BSO_ser, BSO_num, BSO_TypeID, null);
        }
        
        /// <remarks/>
        public void Block_BSOAsync(string BSO_ser, string BSO_num, int BSO_TypeID, object userState) {
            if ((this.Block_BSOOperationCompleted == null)) {
                this.Block_BSOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBlock_BSOOperationCompleted);
            }
            this.InvokeAsync("Block_BSO", new object[] {
                        BSO_ser,
                        BSO_num,
                        BSO_TypeID}, this.Block_BSOOperationCompleted, userState);
        }
        
        private void OnBlock_BSOOperationCompleted(object arg) {
            if ((this.Block_BSOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Block_BSOCompleted(this, new Block_BSOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#WriteStatistic", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int WriteStatistic(string comment) {
            object[] results = this.Invoke("WriteStatistic", new object[] {
                        comment});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void WriteStatisticAsync(string comment) {
            this.WriteStatisticAsync(comment, null);
        }
        
        /// <remarks/>
        public void WriteStatisticAsync(string comment, object userState) {
            if ((this.WriteStatisticOperationCompleted == null)) {
                this.WriteStatisticOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteStatisticOperationCompleted);
            }
            this.InvokeAsync("WriteStatistic", new object[] {
                        comment}, this.WriteStatisticOperationCompleted, userState);
        }
        
        private void OnWriteStatisticOperationCompleted(object arg) {
            if ((this.WriteStatisticCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteStatisticCompleted(this, new WriteStatisticCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#CheckOurNPFClient", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int CheckOurNPFClient(string Snils) {
            object[] results = this.Invoke("CheckOurNPFClient", new object[] {
                        Snils});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CheckOurNPFClientAsync(string Snils) {
            this.CheckOurNPFClientAsync(Snils, null);
        }
        
        /// <remarks/>
        public void CheckOurNPFClientAsync(string Snils, object userState) {
            if ((this.CheckOurNPFClientOperationCompleted == null)) {
                this.CheckOurNPFClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOurNPFClientOperationCompleted);
            }
            this.InvokeAsync("CheckOurNPFClient", new object[] {
                        Snils}, this.CheckOurNPFClientOperationCompleted, userState);
        }
        
        private void OnCheckOurNPFClientOperationCompleted(object arg) {
            if ((this.CheckOurNPFClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckOurNPFClientCompleted(this, new CheckOurNPFClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetNPFAgent", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetNPFAgent(string LNR) {
            object[] results = this.Invoke("GetNPFAgent", new object[] {
                        LNR});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNPFAgentAsync(string LNR) {
            this.GetNPFAgentAsync(LNR, null);
        }
        
        /// <remarks/>
        public void GetNPFAgentAsync(string LNR, object userState) {
            if ((this.GetNPFAgentOperationCompleted == null)) {
                this.GetNPFAgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNPFAgentOperationCompleted);
            }
            this.InvokeAsync("GetNPFAgent", new object[] {
                        LNR}, this.GetNPFAgentOperationCompleted, userState);
        }
        
        private void OnGetNPFAgentOperationCompleted(object arg) {
            if ((this.GetNPFAgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNPFAgentCompleted(this, new GetNPFAgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#PassportIsBad", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int PassportIsBad(string PASSP_SERIES, string PASSP_NUMBER) {
            object[] results = this.Invoke("PassportIsBad", new object[] {
                        PASSP_SERIES,
                        PASSP_NUMBER});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PassportIsBadAsync(string PASSP_SERIES, string PASSP_NUMBER) {
            this.PassportIsBadAsync(PASSP_SERIES, PASSP_NUMBER, null);
        }
        
        /// <remarks/>
        public void PassportIsBadAsync(string PASSP_SERIES, string PASSP_NUMBER, object userState) {
            if ((this.PassportIsBadOperationCompleted == null)) {
                this.PassportIsBadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPassportIsBadOperationCompleted);
            }
            this.InvokeAsync("PassportIsBad", new object[] {
                        PASSP_SERIES,
                        PASSP_NUMBER}, this.PassportIsBadOperationCompleted, userState);
        }
        
        private void OnPassportIsBadOperationCompleted(object arg) {
            if ((this.PassportIsBadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PassportIsBadCompleted(this, new PassportIsBadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetServerDateTime", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetServerDateTime() {
            object[] results = this.Invoke("GetServerDateTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerDateTimeAsync() {
            this.GetServerDateTimeAsync(null);
        }
        
        /// <remarks/>
        public void GetServerDateTimeAsync(object userState) {
            if ((this.GetServerDateTimeOperationCompleted == null)) {
                this.GetServerDateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerDateTimeOperationCompleted);
            }
            this.InvokeAsync("GetServerDateTime", new object[0], this.GetServerDateTimeOperationCompleted, userState);
        }
        
        private void OnGetServerDateTimeOperationCompleted(object arg) {
            if ((this.GetServerDateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerDateTimeCompleted(this, new GetServerDateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#WritePolicyToMGDB", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string WritePolicyToMGDB(string XML) {
            object[] results = this.Invoke("WritePolicyToMGDB", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WritePolicyToMGDBAsync(string XML) {
            this.WritePolicyToMGDBAsync(XML, null);
        }
        
        /// <remarks/>
        public void WritePolicyToMGDBAsync(string XML, object userState) {
            if ((this.WritePolicyToMGDBOperationCompleted == null)) {
                this.WritePolicyToMGDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWritePolicyToMGDBOperationCompleted);
            }
            this.InvokeAsync("WritePolicyToMGDB", new object[] {
                        XML}, this.WritePolicyToMGDBOperationCompleted, userState);
        }
        
        private void OnWritePolicyToMGDBOperationCompleted(object arg) {
            if ((this.WritePolicyToMGDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WritePolicyToMGDBCompleted(this, new WritePolicyToMGDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#Check_APO2_Last_Versions", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Check_APO2_Last_Versions(string XML) {
            object[] results = this.Invoke("Check_APO2_Last_Versions", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_APO2_Last_VersionsAsync(string XML) {
            this.Check_APO2_Last_VersionsAsync(XML, null);
        }
        
        /// <remarks/>
        public void Check_APO2_Last_VersionsAsync(string XML, object userState) {
            if ((this.Check_APO2_Last_VersionsOperationCompleted == null)) {
                this.Check_APO2_Last_VersionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_APO2_Last_VersionsOperationCompleted);
            }
            this.InvokeAsync("Check_APO2_Last_Versions", new object[] {
                        XML}, this.Check_APO2_Last_VersionsOperationCompleted, userState);
        }
        
        private void OnCheck_APO2_Last_VersionsOperationCompleted(object arg) {
            if ((this.Check_APO2_Last_VersionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_APO2_Last_VersionsCompleted(this, new Check_APO2_Last_VersionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#GetAgentsByLNR_INN", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetAgentsByLNR_INN(string LNR_INN, int fuz_yur_ii) {
            object[] results = this.Invoke("GetAgentsByLNR_INN", new object[] {
                        LNR_INN,
                        fuz_yur_ii});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentsByLNR_INNAsync(string LNR_INN, int fuz_yur_ii) {
            this.GetAgentsByLNR_INNAsync(LNR_INN, fuz_yur_ii, null);
        }
        
        /// <remarks/>
        public void GetAgentsByLNR_INNAsync(string LNR_INN, int fuz_yur_ii, object userState) {
            if ((this.GetAgentsByLNR_INNOperationCompleted == null)) {
                this.GetAgentsByLNR_INNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentsByLNR_INNOperationCompleted);
            }
            this.InvokeAsync("GetAgentsByLNR_INN", new object[] {
                        LNR_INN,
                        fuz_yur_ii}, this.GetAgentsByLNR_INNOperationCompleted, userState);
        }
        
        private void OnGetAgentsByLNR_INNOperationCompleted(object arg) {
            if ((this.GetAgentsByLNR_INNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentsByLNR_INNCompleted(this, new GetAgentsByLNR_INNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#ConfirmModify", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool ConfirmModify(string Series, string Number, string AgentLnr) {
            object[] results = this.Invoke("ConfirmModify", new object[] {
                        Series,
                        Number,
                        AgentLnr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmModifyAsync(string Series, string Number, string AgentLnr) {
            this.ConfirmModifyAsync(Series, Number, AgentLnr, null);
        }
        
        /// <remarks/>
        public void ConfirmModifyAsync(string Series, string Number, string AgentLnr, object userState) {
            if ((this.ConfirmModifyOperationCompleted == null)) {
                this.ConfirmModifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmModifyOperationCompleted);
            }
            this.InvokeAsync("ConfirmModify", new object[] {
                        Series,
                        Number,
                        AgentLnr}, this.ConfirmModifyOperationCompleted, userState);
        }
        
        private void OnConfirmModifyOperationCompleted(object arg) {
            if ((this.ConfirmModifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmModifyCompleted(this, new ConfirmModifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#IsAllowedModify", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool IsAllowedModify(string Series, string Number, string AgentLnr) {
            object[] results = this.Invoke("IsAllowedModify", new object[] {
                        Series,
                        Number,
                        AgentLnr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsAllowedModifyAsync(string Series, string Number, string AgentLnr) {
            this.IsAllowedModifyAsync(Series, Number, AgentLnr, null);
        }
        
        /// <remarks/>
        public void IsAllowedModifyAsync(string Series, string Number, string AgentLnr, object userState) {
            if ((this.IsAllowedModifyOperationCompleted == null)) {
                this.IsAllowedModifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAllowedModifyOperationCompleted);
            }
            this.InvokeAsync("IsAllowedModify", new object[] {
                        Series,
                        Number,
                        AgentLnr}, this.IsAllowedModifyOperationCompleted, userState);
        }
        
        private void OnIsAllowedModifyOperationCompleted(object arg) {
            if ((this.IsAllowedModifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAllowedModifyCompleted(this, new IsAllowedModifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#WriteToSplunk", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        public void WriteToSplunk(string CorrelationId, string Action, string Message, string host, string ext) {
            this.Invoke("WriteToSplunk", new object[] {
                        CorrelationId,
                        Action,
                        Message,
                        host,
                        ext});
        }
        
        /// <remarks/>
        public void WriteToSplunkAsync(string CorrelationId, string Action, string Message, string host, string ext) {
            this.WriteToSplunkAsync(CorrelationId, Action, Message, host, ext, null);
        }
        
        /// <remarks/>
        public void WriteToSplunkAsync(string CorrelationId, string Action, string Message, string host, string ext, object userState) {
            if ((this.WriteToSplunkOperationCompleted == null)) {
                this.WriteToSplunkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteToSplunkOperationCompleted);
            }
            this.InvokeAsync("WriteToSplunk", new object[] {
                        CorrelationId,
                        Action,
                        Message,
                        host,
                        ext}, this.WriteToSplunkOperationCompleted, userState);
        }
        
        private void OnWriteToSplunkOperationCompleted(object arg) {
            if ((this.WriteToSplunkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteToSplunkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:APO2_ARM_READER_c-IAPO2_ARM_READER#WriteToSplunk2", RequestNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER", ResponseNamespace="urn:APO2_ARM_READER_c-IAPO2_ARM_READER")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string WriteToSplunk2(string Index, string ParamsList, string ext, string SpErrors) {
            object[] results = this.Invoke("WriteToSplunk2", new object[] {
                        Index,
                        ParamsList,
                        ext,
                        SpErrors});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WriteToSplunk2Async(string Index, string ParamsList, string ext, string SpErrors) {
            this.WriteToSplunk2Async(Index, ParamsList, ext, SpErrors, null);
        }
        
        /// <remarks/>
        public void WriteToSplunk2Async(string Index, string ParamsList, string ext, string SpErrors, object userState) {
            if ((this.WriteToSplunk2OperationCompleted == null)) {
                this.WriteToSplunk2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteToSplunk2OperationCompleted);
            }
            this.InvokeAsync("WriteToSplunk2", new object[] {
                        Index,
                        ParamsList,
                        ext,
                        SpErrors}, this.WriteToSplunk2OperationCompleted, userState);
        }
        
        private void OnWriteToSplunk2OperationCompleted(object arg) {
            if ((this.WriteToSplunk2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteToSplunk2Completed(this, new WriteToSplunk2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDataA4CompletedEventHandler(object sender, GetDataA4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataA4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataA4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetKbmToCompletedEventHandler(object sender, GetKbmToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKbmToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKbmToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetInfoContractsCompletedEventHandler(object sender, GetInfoContractsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoContractsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoContractsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Check_BSOCompletedEventHandler(object sender, Check_BSOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_BSOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_BSOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Check_BSO2CompletedEventHandler(object sender, Check_BSO2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_BSO2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_BSO2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Check_BSO3CompletedEventHandler(object sender, Check_BSO3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_BSO3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_BSO3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Check_BSO4CompletedEventHandler(object sender, Check_BSO4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_BSO4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_BSO4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Check_BSO5CompletedEventHandler(object sender, Check_BSO5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_BSO5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_BSO5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Check_BSO6CompletedEventHandler(object sender, Check_BSO6CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_BSO6CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_BSO6CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetFactDatabyAgentIDCompletedEventHandler(object sender, GetFactDatabyAgentIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFactDatabyAgentIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFactDatabyAgentIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckPreferentialExtensionCompletedEventHandler(object sender, CheckPreferentialExtensionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPreferentialExtensionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPreferentialExtensionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetVPNUserCompletedEventHandler(object sender, GetVPNUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVPNUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVPNUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Block_BSOCompletedEventHandler(object sender, Block_BSOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Block_BSOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Block_BSOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void WriteStatisticCompletedEventHandler(object sender, WriteStatisticCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteStatisticCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteStatisticCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckOurNPFClientCompletedEventHandler(object sender, CheckOurNPFClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckOurNPFClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckOurNPFClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetNPFAgentCompletedEventHandler(object sender, GetNPFAgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNPFAgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNPFAgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PassportIsBadCompletedEventHandler(object sender, PassportIsBadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PassportIsBadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PassportIsBadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetServerDateTimeCompletedEventHandler(object sender, GetServerDateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void WritePolicyToMGDBCompletedEventHandler(object sender, WritePolicyToMGDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WritePolicyToMGDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WritePolicyToMGDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Check_APO2_Last_VersionsCompletedEventHandler(object sender, Check_APO2_Last_VersionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_APO2_Last_VersionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_APO2_Last_VersionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAgentsByLNR_INNCompletedEventHandler(object sender, GetAgentsByLNR_INNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentsByLNR_INNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentsByLNR_INNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConfirmModifyCompletedEventHandler(object sender, ConfirmModifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmModifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmModifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void IsAllowedModifyCompletedEventHandler(object sender, IsAllowedModifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAllowedModifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAllowedModifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void WriteToSplunkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void WriteToSplunk2CompletedEventHandler(object sender, WriteToSplunk2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteToSplunk2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteToSplunk2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591