//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiceIntegration.wsCardService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ICard_create_SOAP_Servicebinding", Namespace="http://tempuri.org/")]
    public partial class ICard_create_SOAP_Serviceservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNewCardNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback CardSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback CardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CardNewRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CardCancelRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ICard_create_SOAP_Serviceservice() {
            this.Url = global::ServiceIntegration.Properties.Settings.Default.ServiceIntegration_wsCardService_ICard_create_SOAP_Serviceservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNewCardNumberCompletedEventHandler GetNewCardNumberCompleted;
        
        /// <remarks/>
        public event CardSearchCompletedEventHandler CardSearchCompleted;
        
        /// <remarks/>
        public event CardInfoCompletedEventHandler CardInfoCompleted;
        
        /// <remarks/>
        public event CardNewRequestCompletedEventHandler CardNewRequestCompleted;
        
        /// <remarks/>
        public event CardCancelRequestCompletedEventHandler CardCancelRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service#GetNewCardNumber", RequestNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service", ResponseNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetNewCardNumber(string CardXMLData) {
            object[] results = this.Invoke("GetNewCardNumber", new object[] {
                        CardXMLData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewCardNumberAsync(string CardXMLData) {
            this.GetNewCardNumberAsync(CardXMLData, null);
        }
        
        /// <remarks/>
        public void GetNewCardNumberAsync(string CardXMLData, object userState) {
            if ((this.GetNewCardNumberOperationCompleted == null)) {
                this.GetNewCardNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewCardNumberOperationCompleted);
            }
            this.InvokeAsync("GetNewCardNumber", new object[] {
                        CardXMLData}, this.GetNewCardNumberOperationCompleted, userState);
        }
        
        private void OnGetNewCardNumberOperationCompleted(object arg) {
            if ((this.GetNewCardNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewCardNumberCompleted(this, new GetNewCardNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service#CardSearch", RequestNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service", ResponseNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CardSearch(string Search_Condition, string Sys_UID) {
            object[] results = this.Invoke("CardSearch", new object[] {
                        Search_Condition,
                        Sys_UID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CardSearchAsync(string Search_Condition, string Sys_UID) {
            this.CardSearchAsync(Search_Condition, Sys_UID, null);
        }
        
        /// <remarks/>
        public void CardSearchAsync(string Search_Condition, string Sys_UID, object userState) {
            if ((this.CardSearchOperationCompleted == null)) {
                this.CardSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardSearchOperationCompleted);
            }
            this.InvokeAsync("CardSearch", new object[] {
                        Search_Condition,
                        Sys_UID}, this.CardSearchOperationCompleted, userState);
        }
        
        private void OnCardSearchOperationCompleted(object arg) {
            if ((this.CardSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardSearchCompleted(this, new CardSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service#CardInfo", RequestNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service", ResponseNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CardInfo(string Card_Number, string Sys_UID) {
            object[] results = this.Invoke("CardInfo", new object[] {
                        Card_Number,
                        Sys_UID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CardInfoAsync(string Card_Number, string Sys_UID) {
            this.CardInfoAsync(Card_Number, Sys_UID, null);
        }
        
        /// <remarks/>
        public void CardInfoAsync(string Card_Number, string Sys_UID, object userState) {
            if ((this.CardInfoOperationCompleted == null)) {
                this.CardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardInfoOperationCompleted);
            }
            this.InvokeAsync("CardInfo", new object[] {
                        Card_Number,
                        Sys_UID}, this.CardInfoOperationCompleted, userState);
        }
        
        private void OnCardInfoOperationCompleted(object arg) {
            if ((this.CardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardInfoCompleted(this, new CardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service#CardNewRequest", RequestNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service", ResponseNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CardNewRequest(string RequestXMLData, string Sys_UID) {
            object[] results = this.Invoke("CardNewRequest", new object[] {
                        RequestXMLData,
                        Sys_UID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CardNewRequestAsync(string RequestXMLData, string Sys_UID) {
            this.CardNewRequestAsync(RequestXMLData, Sys_UID, null);
        }
        
        /// <remarks/>
        public void CardNewRequestAsync(string RequestXMLData, string Sys_UID, object userState) {
            if ((this.CardNewRequestOperationCompleted == null)) {
                this.CardNewRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardNewRequestOperationCompleted);
            }
            this.InvokeAsync("CardNewRequest", new object[] {
                        RequestXMLData,
                        Sys_UID}, this.CardNewRequestOperationCompleted, userState);
        }
        
        private void OnCardNewRequestOperationCompleted(object arg) {
            if ((this.CardNewRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardNewRequestCompleted(this, new CardNewRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service#CardCancelRequest", RequestNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service", ResponseNamespace="urn:Card_create_SOAP_Service_c-ICard_create_SOAP_Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CardCancelRequest(int Request_ID, string Cancel_Reason, string Sys_UID) {
            object[] results = this.Invoke("CardCancelRequest", new object[] {
                        Request_ID,
                        Cancel_Reason,
                        Sys_UID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CardCancelRequestAsync(int Request_ID, string Cancel_Reason, string Sys_UID) {
            this.CardCancelRequestAsync(Request_ID, Cancel_Reason, Sys_UID, null);
        }
        
        /// <remarks/>
        public void CardCancelRequestAsync(int Request_ID, string Cancel_Reason, string Sys_UID, object userState) {
            if ((this.CardCancelRequestOperationCompleted == null)) {
                this.CardCancelRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardCancelRequestOperationCompleted);
            }
            this.InvokeAsync("CardCancelRequest", new object[] {
                        Request_ID,
                        Cancel_Reason,
                        Sys_UID}, this.CardCancelRequestOperationCompleted, userState);
        }
        
        private void OnCardCancelRequestOperationCompleted(object arg) {
            if ((this.CardCancelRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardCancelRequestCompleted(this, new CardCancelRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetNewCardNumberCompletedEventHandler(object sender, GetNewCardNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewCardNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewCardNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CardSearchCompletedEventHandler(object sender, CardSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CardSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CardInfoCompletedEventHandler(object sender, CardInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CardNewRequestCompletedEventHandler(object sender, CardNewRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardNewRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CardNewRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CardCancelRequestCompletedEventHandler(object sender, CardCancelRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardCancelRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CardCancelRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591