//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceIntegration.VehicleAggregator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types", ConfigurationName="VehicleAggregator.VehicleAggregator")]
    public interface VehicleAggregator {
        
        // CODEGEN: Generating message contract since the operation aggregate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(costData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseTechData))]
        ServiceIntegration.VehicleAggregator.aggregateResponse aggregate(ServiceIntegration.VehicleAggregator.aggregate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceIntegration.VehicleAggregator.aggregateResponse> aggregateAsync(ServiceIntegration.VehicleAggregator.aggregate request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestBusinessData businessDataField;
        
        private requestTechData techDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestBusinessData businessData {
            get {
                return this.businessDataField;
            }
            set {
                this.businessDataField = value;
                this.RaisePropertyChanged("businessData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public requestTechData techData {
            get {
                return this.techDataField;
            }
            set {
                this.techDataField = value;
                this.RaisePropertyChanged("techData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class requestBusinessData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyNumberField;
        
        private string grzField;
        
        private string vinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bodyNumber {
            get {
                return this.bodyNumberField;
            }
            set {
                this.bodyNumberField = value;
                this.RaisePropertyChanged("bodyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string grz {
            get {
                return this.grzField;
            }
            set {
                this.grzField = value;
                this.RaisePropertyChanged("grz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class responseTechData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actionIdField;
        
        private string correlationIdField;
        
        private string errorDescriptionField;
        
        private string responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string actionId {
            get {
                return this.actionIdField;
            }
            set {
                this.actionIdField = value;
                this.RaisePropertyChanged("actionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correlationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
                this.RaisePropertyChanged("correlationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class motorwert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyTypeField;
        
        private string carEngineField;
        
        private string carModificationField;
        
        private int doorsField;
        
        private bool doorsFieldSpecified;
        
        private int maxWeightField;
        
        private bool maxWeightFieldSpecified;
        
        private decimal motorwertEnginePowerField;
        
        private bool motorwertEnginePowerFieldSpecified;
        
        private string motorwertIdField;
        
        private int priceField;
        
        private bool priceFieldSpecified;
        
        private int seatsField;
        
        private bool seatsFieldSpecified;
        
        private string transmissionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bodyType {
            get {
                return this.bodyTypeField;
            }
            set {
                this.bodyTypeField = value;
                this.RaisePropertyChanged("bodyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string carEngine {
            get {
                return this.carEngineField;
            }
            set {
                this.carEngineField = value;
                this.RaisePropertyChanged("carEngine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string carModification {
            get {
                return this.carModificationField;
            }
            set {
                this.carModificationField = value;
                this.RaisePropertyChanged("carModification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int doors {
            get {
                return this.doorsField;
            }
            set {
                this.doorsField = value;
                this.RaisePropertyChanged("doors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doorsSpecified {
            get {
                return this.doorsFieldSpecified;
            }
            set {
                this.doorsFieldSpecified = value;
                this.RaisePropertyChanged("doorsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int maxWeight {
            get {
                return this.maxWeightField;
            }
            set {
                this.maxWeightField = value;
                this.RaisePropertyChanged("maxWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxWeightSpecified {
            get {
                return this.maxWeightFieldSpecified;
            }
            set {
                this.maxWeightFieldSpecified = value;
                this.RaisePropertyChanged("maxWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal motorwertEnginePower {
            get {
                return this.motorwertEnginePowerField;
            }
            set {
                this.motorwertEnginePowerField = value;
                this.RaisePropertyChanged("motorwertEnginePower");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool motorwertEnginePowerSpecified {
            get {
                return this.motorwertEnginePowerFieldSpecified;
            }
            set {
                this.motorwertEnginePowerFieldSpecified = value;
                this.RaisePropertyChanged("motorwertEnginePowerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string motorwertId {
            get {
                return this.motorwertIdField;
            }
            set {
                this.motorwertIdField = value;
                this.RaisePropertyChanged("motorwertId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatsSpecified {
            get {
                return this.seatsFieldSpecified;
            }
            set {
                this.seatsFieldSpecified = value;
                this.RaisePropertyChanged("seatsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string transmissionType {
            get {
                return this.transmissionTypeField;
            }
            set {
                this.transmissionTypeField = value;
                this.RaisePropertyChanged("transmissionType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(costDataWithVat))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class costData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class costDataWithVat : costData {
        
        private bool vatIncludedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool vatIncluded {
            get {
                return this.vatIncludedField;
            }
            set {
                this.vatIncludedField = value;
                this.RaisePropertyChanged("vatIncluded");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class historyHeaderData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private localDateTime calculationDateTimeField;
        
        private costDataWithVat totalCostField;
        
        private bool totalLossField;
        
        private bool totalLossFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime calculationDateTime {
            get {
                return this.calculationDateTimeField;
            }
            set {
                this.calculationDateTimeField = value;
                this.RaisePropertyChanged("calculationDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public costDataWithVat totalCost {
            get {
                return this.totalCostField;
            }
            set {
                this.totalCostField = value;
                this.RaisePropertyChanged("totalCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool totalLoss {
            get {
                return this.totalLossField;
            }
            set {
                this.totalLossField = value;
                this.RaisePropertyChanged("totalLoss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalLossSpecified {
            get {
                return this.totalLossFieldSpecified;
            }
            set {
                this.totalLossFieldSpecified = value;
                this.RaisePropertyChanged("totalLossSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class enginePower : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal enginePowerHPField;
        
        private bool enginePowerHPFieldSpecified;
        
        private decimal enginePowerKWField;
        
        private bool enginePowerKWFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal enginePowerHP {
            get {
                return this.enginePowerHPField;
            }
            set {
                this.enginePowerHPField = value;
                this.RaisePropertyChanged("enginePowerHP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enginePowerHPSpecified {
            get {
                return this.enginePowerHPFieldSpecified;
            }
            set {
                this.enginePowerHPFieldSpecified = value;
                this.RaisePropertyChanged("enginePowerHPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal enginePowerKW {
            get {
                return this.enginePowerKWField;
            }
            set {
                this.enginePowerKWField = value;
                this.RaisePropertyChanged("enginePowerKW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enginePowerKWSpecified {
            get {
                return this.enginePowerKWFieldSpecified;
            }
            set {
                this.enginePowerKWFieldSpecified = value;
                this.RaisePropertyChanged("enginePowerKWSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class vehicleDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string docNumberField;
        
        private string docSeriesField;
        
        private string docTypeField;
        
        private localDate issueDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string docNumber {
            get {
                return this.docNumberField;
            }
            set {
                this.docNumberField = value;
                this.RaisePropertyChanged("docNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string docSeries {
            get {
                return this.docSeriesField;
            }
            set {
                this.docSeriesField = value;
                this.RaisePropertyChanged("docSeries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string docType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("docType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDate issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("issueDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class vehicleData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mileageField;
        
        private bool mileageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int mileage {
            get {
                return this.mileageField;
            }
            set {
                this.mileageField = value;
                this.RaisePropertyChanged("mileage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mileageSpecified {
            get {
                return this.mileageFieldSpecified;
            }
            set {
                this.mileageFieldSpecified = value;
                this.RaisePropertyChanged("mileageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class claimData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private localDate creationDateField;
        
        private string idField;
        
        private vehicleData vehicleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDate creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("creationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public vehicleData vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
                this.RaisePropertyChanged("vehicle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class aggregatedData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyNumberField;
        
        private string bodyTypeField;
        
        private string carEngineField;
        
        private string carModificationField;
        
        private string categoryField;
        
        private string chassisNumberField;
        
        private claimData[] claimsDataField;
        
        private vehicleDocument[] docsField;
        
        private int doorsField;
        
        private bool doorsFieldSpecified;
        
        private int engineCapacityField;
        
        private bool engineCapacityFieldSpecified;
        
        private enginePower enginePowerField;
        
        private string engineTypeField;
        
        private localDate firstRegistrationDateField;
        
        private historyHeaderData[] historyDataField;
        
        private localDate lastRegistrationDateField;
        
        private string markField;
        
        private int maxPriceField;
        
        private bool maxPriceFieldSpecified;
        
        private int maxWeightField;
        
        private bool maxWeightFieldSpecified;
        
        private int midPriceField;
        
        private bool midPriceFieldSpecified;
        
        private int minPriceField;
        
        private bool minPriceFieldSpecified;
        
        private string modelField;
        
        private motorwert[] motorwertEntriesField;
        
        private string reg_numField;
        
        private string rsaCodeField;
        
        private int seatsField;
        
        private bool seatsFieldSpecified;
        
        private string submodelField;
        
        private string transmissionTypeField;
        
        private string vehicleTypeField;
        
        private string vinField;
        
        private int yearOfProductionField;
        
        private bool yearOfProductionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bodyNumber {
            get {
                return this.bodyNumberField;
            }
            set {
                this.bodyNumberField = value;
                this.RaisePropertyChanged("bodyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bodyType {
            get {
                return this.bodyTypeField;
            }
            set {
                this.bodyTypeField = value;
                this.RaisePropertyChanged("bodyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string carEngine {
            get {
                return this.carEngineField;
            }
            set {
                this.carEngineField = value;
                this.RaisePropertyChanged("carEngine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string carModification {
            get {
                return this.carModificationField;
            }
            set {
                this.carModificationField = value;
                this.RaisePropertyChanged("carModification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string chassisNumber {
            get {
                return this.chassisNumberField;
            }
            set {
                this.chassisNumberField = value;
                this.RaisePropertyChanged("chassisNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("claims", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public claimData[] claimsData {
            get {
                return this.claimsDataField;
            }
            set {
                this.claimsDataField = value;
                this.RaisePropertyChanged("claimsData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("docs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public vehicleDocument[] docs {
            get {
                return this.docsField;
            }
            set {
                this.docsField = value;
                this.RaisePropertyChanged("docs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int doors {
            get {
                return this.doorsField;
            }
            set {
                this.doorsField = value;
                this.RaisePropertyChanged("doors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doorsSpecified {
            get {
                return this.doorsFieldSpecified;
            }
            set {
                this.doorsFieldSpecified = value;
                this.RaisePropertyChanged("doorsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int engineCapacity {
            get {
                return this.engineCapacityField;
            }
            set {
                this.engineCapacityField = value;
                this.RaisePropertyChanged("engineCapacity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool engineCapacitySpecified {
            get {
                return this.engineCapacityFieldSpecified;
            }
            set {
                this.engineCapacityFieldSpecified = value;
                this.RaisePropertyChanged("engineCapacitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public enginePower enginePower {
            get {
                return this.enginePowerField;
            }
            set {
                this.enginePowerField = value;
                this.RaisePropertyChanged("enginePower");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string engineType {
            get {
                return this.engineTypeField;
            }
            set {
                this.engineTypeField = value;
                this.RaisePropertyChanged("engineType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public localDate firstRegistrationDate {
            get {
                return this.firstRegistrationDateField;
            }
            set {
                this.firstRegistrationDateField = value;
                this.RaisePropertyChanged("firstRegistrationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public historyHeaderData[] historyData {
            get {
                return this.historyDataField;
            }
            set {
                this.historyDataField = value;
                this.RaisePropertyChanged("historyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public localDate lastRegistrationDate {
            get {
                return this.lastRegistrationDateField;
            }
            set {
                this.lastRegistrationDateField = value;
                this.RaisePropertyChanged("lastRegistrationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("mark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int maxPrice {
            get {
                return this.maxPriceField;
            }
            set {
                this.maxPriceField = value;
                this.RaisePropertyChanged("maxPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPriceSpecified {
            get {
                return this.maxPriceFieldSpecified;
            }
            set {
                this.maxPriceFieldSpecified = value;
                this.RaisePropertyChanged("maxPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int maxWeight {
            get {
                return this.maxWeightField;
            }
            set {
                this.maxWeightField = value;
                this.RaisePropertyChanged("maxWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxWeightSpecified {
            get {
                return this.maxWeightFieldSpecified;
            }
            set {
                this.maxWeightFieldSpecified = value;
                this.RaisePropertyChanged("maxWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int midPrice {
            get {
                return this.midPriceField;
            }
            set {
                this.midPriceField = value;
                this.RaisePropertyChanged("midPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool midPriceSpecified {
            get {
                return this.midPriceFieldSpecified;
            }
            set {
                this.midPriceFieldSpecified = value;
                this.RaisePropertyChanged("midPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int minPrice {
            get {
                return this.minPriceField;
            }
            set {
                this.minPriceField = value;
                this.RaisePropertyChanged("minPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minPriceSpecified {
            get {
                return this.minPriceFieldSpecified;
            }
            set {
                this.minPriceFieldSpecified = value;
                this.RaisePropertyChanged("minPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("motorwertEntries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public motorwert[] motorwertEntries {
            get {
                return this.motorwertEntriesField;
            }
            set {
                this.motorwertEntriesField = value;
                this.RaisePropertyChanged("motorwertEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string reg_num {
            get {
                return this.reg_numField;
            }
            set {
                this.reg_numField = value;
                this.RaisePropertyChanged("reg_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string rsaCode {
            get {
                return this.rsaCodeField;
            }
            set {
                this.rsaCodeField = value;
                this.RaisePropertyChanged("rsaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public int seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatsSpecified {
            get {
                return this.seatsFieldSpecified;
            }
            set {
                this.seatsFieldSpecified = value;
                this.RaisePropertyChanged("seatsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string submodel {
            get {
                return this.submodelField;
            }
            set {
                this.submodelField = value;
                this.RaisePropertyChanged("submodel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string transmissionType {
            get {
                return this.transmissionTypeField;
            }
            set {
                this.transmissionTypeField = value;
                this.RaisePropertyChanged("transmissionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string vehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
                this.RaisePropertyChanged("vehicleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public int yearOfProduction {
            get {
                return this.yearOfProductionField;
            }
            set {
                this.yearOfProductionField = value;
                this.RaisePropertyChanged("yearOfProduction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearOfProductionSpecified {
            get {
                return this.yearOfProductionFieldSpecified;
            }
            set {
                this.yearOfProductionFieldSpecified = value;
                this.RaisePropertyChanged("yearOfProductionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class responseBusinessData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private aggregatedData aggregateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public aggregatedData aggregate {
            get {
                return this.aggregateField;
            }
            set {
                this.aggregateField = value;
                this.RaisePropertyChanged("aggregate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseBusinessData businessDataField;
        
        private responseTechData techDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseBusinessData businessData {
            get {
                return this.businessDataField;
            }
            set {
                this.businessDataField = value;
                this.RaisePropertyChanged("businessData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public responseTechData techData {
            get {
                return this.techDataField;
            }
            set {
                this.techDataField = value;
                this.RaisePropertyChanged("techData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(requestTechData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public abstract partial class baseTechData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actionIdField;
        
        private string correlationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string actionId {
            get {
                return this.actionIdField;
            }
            set {
                this.actionIdField = value;
                this.RaisePropertyChanged("actionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correlationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
                this.RaisePropertyChanged("correlationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types")]
    public partial class requestTechData : baseTechData {
        
        private bool disableCacheReadsField;
        
        private bool disableCacheWritesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool disableCacheReads {
            get {
                return this.disableCacheReadsField;
            }
            set {
                this.disableCacheReadsField = value;
                this.RaisePropertyChanged("disableCacheReads");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool disableCacheWrites {
            get {
                return this.disableCacheWritesField;
            }
            set {
                this.disableCacheWritesField = value;
                this.RaisePropertyChanged("disableCacheWrites");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aggregate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rgs.ru/vehicle-aggregator/v1/types/request", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceIntegration.VehicleAggregator.request aggregateRequest;
        
        public aggregate() {
        }
        
        public aggregate(ServiceIntegration.VehicleAggregator.request aggregateRequest) {
            this.aggregateRequest = aggregateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aggregateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aggregateResponse", Namespace="http://rgs.ru/vehicle-aggregator/v1/types/response", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceIntegration.VehicleAggregator.response aggregateResponse1;
        
        public aggregateResponse() {
        }
        
        public aggregateResponse(ServiceIntegration.VehicleAggregator.response aggregateResponse1) {
            this.aggregateResponse1 = aggregateResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehicleAggregatorChannel : ServiceIntegration.VehicleAggregator.VehicleAggregator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleAggregatorClient : System.ServiceModel.ClientBase<ServiceIntegration.VehicleAggregator.VehicleAggregator>, ServiceIntegration.VehicleAggregator.VehicleAggregator {
        
        public VehicleAggregatorClient() {
        }
        
        public VehicleAggregatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleAggregatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleAggregatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleAggregatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceIntegration.VehicleAggregator.aggregateResponse ServiceIntegration.VehicleAggregator.VehicleAggregator.aggregate(ServiceIntegration.VehicleAggregator.aggregate request) {
            return base.Channel.aggregate(request);
        }
        
        public ServiceIntegration.VehicleAggregator.response aggregate(ServiceIntegration.VehicleAggregator.request aggregateRequest) {
            ServiceIntegration.VehicleAggregator.aggregate inValue = new ServiceIntegration.VehicleAggregator.aggregate();
            inValue.aggregateRequest = aggregateRequest;
            ServiceIntegration.VehicleAggregator.aggregateResponse retVal = ((ServiceIntegration.VehicleAggregator.VehicleAggregator)(this)).aggregate(inValue);
            return retVal.aggregateResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIntegration.VehicleAggregator.aggregateResponse> ServiceIntegration.VehicleAggregator.VehicleAggregator.aggregateAsync(ServiceIntegration.VehicleAggregator.aggregate request) {
            return base.Channel.aggregateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.VehicleAggregator.aggregateResponse> aggregateAsync(ServiceIntegration.VehicleAggregator.request aggregateRequest) {
            ServiceIntegration.VehicleAggregator.aggregate inValue = new ServiceIntegration.VehicleAggregator.aggregate();
            inValue.aggregateRequest = aggregateRequest;
            return ((ServiceIntegration.VehicleAggregator.VehicleAggregator)(this)).aggregateAsync(inValue);
        }
    }
}
