//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceIntegration.wsIbService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultOfIbResponseJq_PwuLIi", Namespace="RGS.UFO")]
    [System.SerializableAttribute()]
    public partial class OperationResultOfIbResponseJq_PwuLIi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceIntegration.wsIbService.AdditionalPaymentData AdditionalDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceIntegration.wsIbService.IbResponse DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<string, string[]>[] GrouppedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<string, string>[] ValidationCodeErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ValidationErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] WarningMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceIntegration.wsIbService.AdditionalPaymentData AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceIntegration.wsIbService.IbResponse Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string[]>[] GrouppedErrorMessage {
            get {
                return this.GrouppedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.GrouppedErrorMessageField, value) != true)) {
                    this.GrouppedErrorMessageField = value;
                    this.RaisePropertyChanged("GrouppedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceVersion {
            get {
                return this.ServiceVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceVersionField, value) != true)) {
                    this.ServiceVersionField = value;
                    this.RaisePropertyChanged("ServiceVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] ValidationCodeErrors {
            get {
                return this.ValidationCodeErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationCodeErrorsField, value) != true)) {
                    this.ValidationCodeErrorsField = value;
                    this.RaisePropertyChanged("ValidationCodeErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ValidationErrors {
            get {
                return this.ValidationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationErrorsField, value) != true)) {
                    this.ValidationErrorsField = value;
                    this.RaisePropertyChanged("ValidationErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] WarningMessages {
            get {
                return this.WarningMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningMessagesField, value) != true)) {
                    this.WarningMessagesField = value;
                    this.RaisePropertyChanged("WarningMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalPaymentData", Namespace="")]
    [System.SerializableAttribute()]
    public partial class AdditionalPaymentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatePayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePay {
            get {
                return this.DatePayField;
            }
            set {
                if ((this.DatePayField.Equals(value) != true)) {
                    this.DatePayField = value;
                    this.RaisePropertyChanged("DatePay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayID {
            get {
                return this.PayIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayIDField, value) != true)) {
                    this.PayIDField = value;
                    this.RaisePropertyChanged("PayID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IbResponse", Namespace="http://schemas.datacontract.org/2004/07/RGS.UFO.Interfaces.Models")]
    [System.SerializableAttribute()]
    public partial class IbResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Rgs.Ufo", ConfigurationName="wsIbService.IIbService")]
    public interface IIbService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Rgs.Ufo/IIbService/Call", ReplyAction="Rgs.Ufo/IIbService/CallResponse")]
        ServiceIntegration.wsIbService.OperationResultOfIbResponseJq_PwuLIi Call(string request, System.Nullable<System.Guid> contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Rgs.Ufo/IIbService/Call", ReplyAction="Rgs.Ufo/IIbService/CallResponse")]
        System.Threading.Tasks.Task<ServiceIntegration.wsIbService.OperationResultOfIbResponseJq_PwuLIi> CallAsync(string request, System.Nullable<System.Guid> contractId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIbServiceChannel : ServiceIntegration.wsIbService.IIbService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IbServiceClient : System.ServiceModel.ClientBase<ServiceIntegration.wsIbService.IIbService>, ServiceIntegration.wsIbService.IIbService {
        
        public IbServiceClient() {
        }
        
        public IbServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IbServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceIntegration.wsIbService.OperationResultOfIbResponseJq_PwuLIi Call(string request, System.Nullable<System.Guid> contractId) {
            return base.Channel.Call(request, contractId);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.wsIbService.OperationResultOfIbResponseJq_PwuLIi> CallAsync(string request, System.Nullable<System.Guid> contractId) {
            return base.Channel.CallAsync(request, contractId);
        }
    }
}
