//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceIntegration.wsFileStorage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.filestore.rgs.ru/", ConfigurationName="wsFileStorage.FileStoreAPI")]
    public interface FileStoreAPI {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceIntegration.wsFileStorage.createFileResponse createFile(ServiceIntegration.wsFileStorage.createFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.createFileResponse> createFileAsync(ServiceIntegration.wsFileStorage.createFile request);
        
        // CODEGEN: Parameter 'client' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceIntegration.wsFileStorage.deleteFileResponse deleteFile(ServiceIntegration.wsFileStorage.deleteFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.deleteFileResponse> deleteFileAsync(ServiceIntegration.wsFileStorage.deleteFile request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceIntegration.wsFileStorage.updateFileResponse updateFile(ServiceIntegration.wsFileStorage.updateFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.updateFileResponse> updateFileAsync(ServiceIntegration.wsFileStorage.updateFile request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceIntegration.wsFileStorage.readSignatureResponse readSignature(ServiceIntegration.wsFileStorage.readSignature request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.readSignatureResponse> readSignatureAsync(ServiceIntegration.wsFileStorage.readSignature request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceIntegration.wsFileStorage.existsFileResponse existsFile(ServiceIntegration.wsFileStorage.existsFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.existsFileResponse> existsFileAsync(ServiceIntegration.wsFileStorage.existsFile request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceIntegration.wsFileStorage.readFileResponse readFile(ServiceIntegration.wsFileStorage.readFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.readFileResponse> readFileAsync(ServiceIntegration.wsFileStorage.readFile request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class serviceClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ipField;
        
        private string loginField;
        
        private string macField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("ip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
                this.RaisePropertyChanged("mac");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class fileService_readFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkSumField;
        
        private document documentField;
        
        private signatureHolder signatureHolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string checkSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
                this.RaisePropertyChanged("checkSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public document document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public signatureHolder signatureHolder {
            get {
                return this.signatureHolderField;
            }
            set {
                this.signatureHolderField = value;
                this.RaisePropertyChanged("signatureHolder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class document : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] contentField;
        
        private bool isVideoField;
        
        private bool isVideoFieldSpecified;
        
        private string mimeTypeField;
        
        private long ttlField;
        
        private bool ttlFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isVideo {
            get {
                return this.isVideoField;
            }
            set {
                this.isVideoField = value;
                this.RaisePropertyChanged("isVideo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isVideoSpecified {
            get {
                return this.isVideoFieldSpecified;
            }
            set {
                this.isVideoFieldSpecified = value;
                this.RaisePropertyChanged("isVideoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
                this.RaisePropertyChanged("ttl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttlSpecified {
            get {
                return this.ttlFieldSpecified;
            }
            set {
                this.ttlFieldSpecified = value;
                this.RaisePropertyChanged("ttlSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class signatureHolder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class fileService_existsFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkSumField;
        
        private bool existsField;
        
        private System.DateTime expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private bool isVideoField;
        
        private bool isVideoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string checkSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
                this.RaisePropertyChanged("checkSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
                this.RaisePropertyChanged("exists");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("expirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationDateSpecified {
            get {
                return this.expirationDateFieldSpecified;
            }
            set {
                this.expirationDateFieldSpecified = value;
                this.RaisePropertyChanged("expirationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isVideo {
            get {
                return this.isVideoField;
            }
            set {
                this.isVideoField = value;
                this.RaisePropertyChanged("isVideo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isVideoSpecified {
            get {
                return this.isVideoFieldSpecified;
            }
            set {
                this.isVideoFieldSpecified = value;
                this.RaisePropertyChanged("isVideoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class fileService_readSignatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private signatureHolder signatureHolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public signatureHolder signatureHolder {
            get {
                return this.signatureHolderField;
            }
            set {
                this.signatureHolderField = value;
                this.RaisePropertyChanged("signatureHolder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class fileService_updateFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkSumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string checkSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
                this.RaisePropertyChanged("checkSum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class keyHolder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.filestore.rgs.ru/")]
    public partial class fileService_createFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkSumField;
        
        private keyHolder keyHolderField;
        
        private signatureHolder signatureHolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string checkSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
                this.RaisePropertyChanged("checkSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public keyHolder keyHolder {
            get {
                return this.keyHolderField;
            }
            set {
                this.keyHolderField = value;
                this.RaisePropertyChanged("keyHolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public signatureHolder signatureHolder {
            get {
                return this.signatureHolderField;
            }
            set {
                this.signatureHolderField = value;
                this.RaisePropertyChanged("signatureHolder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFile", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class createFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.serviceClient client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.document document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.signatureHolder signature;
        
        public createFile() {
        }
        
        public createFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.document document, ServiceIntegration.wsFileStorage.signatureHolder signature) {
            this.client = client;
            this.document = document;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFileResponse", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class createFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.fileService_createFileResponse @return;
        
        public createFileResponse() {
        }
        
        public createFileResponse(ServiceIntegration.wsFileStorage.fileService_createFileResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFile", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class deleteFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.serviceClient client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.keyHolder key;
        
        public deleteFile() {
        }
        
        public deleteFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            this.client = client;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFileResponse", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class deleteFileResponse {
        
        public deleteFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFile", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class updateFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.serviceClient client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.keyHolder key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.document document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.signatureHolder signature;
        
        public updateFile() {
        }
        
        public updateFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key, ServiceIntegration.wsFileStorage.document document, ServiceIntegration.wsFileStorage.signatureHolder signature) {
            this.client = client;
            this.key = key;
            this.document = document;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFileResponse", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class updateFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.fileService_updateFileResponse @return;
        
        public updateFileResponse() {
        }
        
        public updateFileResponse(ServiceIntegration.wsFileStorage.fileService_updateFileResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readSignature", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class readSignature {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.serviceClient client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.keyHolder key;
        
        public readSignature() {
        }
        
        public readSignature(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            this.client = client;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readSignatureResponse", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class readSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.fileService_readSignatureResponse @return;
        
        public readSignatureResponse() {
        }
        
        public readSignatureResponse(ServiceIntegration.wsFileStorage.fileService_readSignatureResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="existsFile", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class existsFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.serviceClient client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.keyHolder key;
        
        public existsFile() {
        }
        
        public existsFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            this.client = client;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="existsFileResponse", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class existsFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.fileService_existsFileResponse @return;
        
        public existsFileResponse() {
        }
        
        public existsFileResponse(ServiceIntegration.wsFileStorage.fileService_existsFileResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readFile", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class readFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.serviceClient client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.keyHolder key;
        
        public readFile() {
        }
        
        public readFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            this.client = client;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readFileResponse", WrapperNamespace="http://web.filestore.rgs.ru/", IsWrapped=true)]
    public partial class readFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.filestore.rgs.ru/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIntegration.wsFileStorage.fileService_readFileResponse @return;
        
        public readFileResponse() {
        }
        
        public readFileResponse(ServiceIntegration.wsFileStorage.fileService_readFileResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileStoreAPIChannel : ServiceIntegration.wsFileStorage.FileStoreAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileStoreAPIClient : System.ServiceModel.ClientBase<ServiceIntegration.wsFileStorage.FileStoreAPI>, ServiceIntegration.wsFileStorage.FileStoreAPI {
        
        public FileStoreAPIClient() {
        }
        
        public FileStoreAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileStoreAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileStoreAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileStoreAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceIntegration.wsFileStorage.createFileResponse ServiceIntegration.wsFileStorage.FileStoreAPI.createFile(ServiceIntegration.wsFileStorage.createFile request) {
            return base.Channel.createFile(request);
        }
        
        public ServiceIntegration.wsFileStorage.fileService_createFileResponse createFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.document document, ServiceIntegration.wsFileStorage.signatureHolder signature) {
            ServiceIntegration.wsFileStorage.createFile inValue = new ServiceIntegration.wsFileStorage.createFile();
            inValue.client = client;
            inValue.document = document;
            inValue.signature = signature;
            ServiceIntegration.wsFileStorage.createFileResponse retVal = ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).createFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.createFileResponse> ServiceIntegration.wsFileStorage.FileStoreAPI.createFileAsync(ServiceIntegration.wsFileStorage.createFile request) {
            return base.Channel.createFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.createFileResponse> createFileAsync(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.document document, ServiceIntegration.wsFileStorage.signatureHolder signature) {
            ServiceIntegration.wsFileStorage.createFile inValue = new ServiceIntegration.wsFileStorage.createFile();
            inValue.client = client;
            inValue.document = document;
            inValue.signature = signature;
            return ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).createFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceIntegration.wsFileStorage.deleteFileResponse ServiceIntegration.wsFileStorage.FileStoreAPI.deleteFile(ServiceIntegration.wsFileStorage.deleteFile request) {
            return base.Channel.deleteFile(request);
        }
        
        public void deleteFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.deleteFile inValue = new ServiceIntegration.wsFileStorage.deleteFile();
            inValue.client = client;
            inValue.key = key;
            ServiceIntegration.wsFileStorage.deleteFileResponse retVal = ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).deleteFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.deleteFileResponse> ServiceIntegration.wsFileStorage.FileStoreAPI.deleteFileAsync(ServiceIntegration.wsFileStorage.deleteFile request) {
            return base.Channel.deleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.deleteFileResponse> deleteFileAsync(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.deleteFile inValue = new ServiceIntegration.wsFileStorage.deleteFile();
            inValue.client = client;
            inValue.key = key;
            return ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).deleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceIntegration.wsFileStorage.updateFileResponse ServiceIntegration.wsFileStorage.FileStoreAPI.updateFile(ServiceIntegration.wsFileStorage.updateFile request) {
            return base.Channel.updateFile(request);
        }
        
        public ServiceIntegration.wsFileStorage.fileService_updateFileResponse updateFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key, ServiceIntegration.wsFileStorage.document document, ServiceIntegration.wsFileStorage.signatureHolder signature) {
            ServiceIntegration.wsFileStorage.updateFile inValue = new ServiceIntegration.wsFileStorage.updateFile();
            inValue.client = client;
            inValue.key = key;
            inValue.document = document;
            inValue.signature = signature;
            ServiceIntegration.wsFileStorage.updateFileResponse retVal = ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).updateFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.updateFileResponse> ServiceIntegration.wsFileStorage.FileStoreAPI.updateFileAsync(ServiceIntegration.wsFileStorage.updateFile request) {
            return base.Channel.updateFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.updateFileResponse> updateFileAsync(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key, ServiceIntegration.wsFileStorage.document document, ServiceIntegration.wsFileStorage.signatureHolder signature) {
            ServiceIntegration.wsFileStorage.updateFile inValue = new ServiceIntegration.wsFileStorage.updateFile();
            inValue.client = client;
            inValue.key = key;
            inValue.document = document;
            inValue.signature = signature;
            return ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).updateFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceIntegration.wsFileStorage.readSignatureResponse ServiceIntegration.wsFileStorage.FileStoreAPI.readSignature(ServiceIntegration.wsFileStorage.readSignature request) {
            return base.Channel.readSignature(request);
        }
        
        public ServiceIntegration.wsFileStorage.fileService_readSignatureResponse readSignature(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.readSignature inValue = new ServiceIntegration.wsFileStorage.readSignature();
            inValue.client = client;
            inValue.key = key;
            ServiceIntegration.wsFileStorage.readSignatureResponse retVal = ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).readSignature(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.readSignatureResponse> ServiceIntegration.wsFileStorage.FileStoreAPI.readSignatureAsync(ServiceIntegration.wsFileStorage.readSignature request) {
            return base.Channel.readSignatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.readSignatureResponse> readSignatureAsync(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.readSignature inValue = new ServiceIntegration.wsFileStorage.readSignature();
            inValue.client = client;
            inValue.key = key;
            return ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).readSignatureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceIntegration.wsFileStorage.existsFileResponse ServiceIntegration.wsFileStorage.FileStoreAPI.existsFile(ServiceIntegration.wsFileStorage.existsFile request) {
            return base.Channel.existsFile(request);
        }
        
        public ServiceIntegration.wsFileStorage.fileService_existsFileResponse existsFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.existsFile inValue = new ServiceIntegration.wsFileStorage.existsFile();
            inValue.client = client;
            inValue.key = key;
            ServiceIntegration.wsFileStorage.existsFileResponse retVal = ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).existsFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.existsFileResponse> ServiceIntegration.wsFileStorage.FileStoreAPI.existsFileAsync(ServiceIntegration.wsFileStorage.existsFile request) {
            return base.Channel.existsFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.existsFileResponse> existsFileAsync(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.existsFile inValue = new ServiceIntegration.wsFileStorage.existsFile();
            inValue.client = client;
            inValue.key = key;
            return ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).existsFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceIntegration.wsFileStorage.readFileResponse ServiceIntegration.wsFileStorage.FileStoreAPI.readFile(ServiceIntegration.wsFileStorage.readFile request) {
            return base.Channel.readFile(request);
        }
        
        public ServiceIntegration.wsFileStorage.fileService_readFileResponse readFile(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.readFile inValue = new ServiceIntegration.wsFileStorage.readFile();
            inValue.client = client;
            inValue.key = key;
            ServiceIntegration.wsFileStorage.readFileResponse retVal = ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).readFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.readFileResponse> ServiceIntegration.wsFileStorage.FileStoreAPI.readFileAsync(ServiceIntegration.wsFileStorage.readFile request) {
            return base.Channel.readFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIntegration.wsFileStorage.readFileResponse> readFileAsync(ServiceIntegration.wsFileStorage.serviceClient client, ServiceIntegration.wsFileStorage.keyHolder key) {
            ServiceIntegration.wsFileStorage.readFile inValue = new ServiceIntegration.wsFileStorage.readFile();
            inValue.client = client;
            inValue.key = key;
            return ((ServiceIntegration.wsFileStorage.FileStoreAPI)(this)).readFileAsync(inValue);
        }
    }
}
