//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceIntegration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://arm-apo.ss.rgs.ru/Card_create_SOAP_Service_test/Card_create_SOAP_Service.d" +
            "ll/soap/ICard_create_SOAP_Service")]
        public string ServiceIntegration_wsCardService_ICard_create_SOAP_Serviceservice {
            get {
                return ((string)(this["ServiceIntegration_wsCardService_ICard_create_SOAP_Serviceservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ibqa.rgs.ru:7003/IBSS/SoftRaterWSSoap11HttpPort")]
        public string ServiceIntegration_wsSoftRater_SoftRaterWS {
            get {
                return ((string)(this["ServiceIntegration_wsSoftRater_SoftRaterWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://arm-apo.ss.rgs.ru/apo2_arm_reader.dll/soap/IAPO2_ARM_READER")]
        public string ServiceIntegration_wsArm_IAPO2_ARM_READERservice {
            get {
                return ((string)(this["ServiceIntegration_wsArm_IAPO2_ARM_READERservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://arm-apo.ss.rgs.ru/GenNoDog_test/GenNoDog.dll/soap/IGenNoDog")]
        public string ServiceIntegration_wsNumberGenerator_IGenNoDogservice {
            get {
                return ((string)(this["ServiceIntegration_wsNumberGenerator_IGenNoDogservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://arm-apo.ss.rgs.ru/IDB_RSA_Test/IBD_RSA_WebServ.dll/soap/IIBD_RSA_WebServ")]
        public string ServiceIntegration_wsRsaBso_IIBD_RSA_WebServservice {
            get {
                return ((string)(this["ServiceIntegration_wsRsaBso_IIBD_RSA_WebServservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://arm-apo.ss.rgs.ru/Send_OSAGO_Service_Test/Send_OSAGO_Service.dll/soap/ISen" +
            "d_OSAGO_Service")]
        public string ServiceIntegration_wsRsaSendOsago_ISend_OSAGO_Serviceservice {
            get {
                return ((string)(this["ServiceIntegration_wsRsaSendOsago_ISend_OSAGO_Serviceservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://arm-soap-proxy.api-test.rgs.ru:80/apo2_arm_reader.dll/soap/IAPO2_ARM_READE" +
            "R")]
        public string ServiceIntegration_wsArmProxy_IAPO2_ARM_READERservice {
            get {
                return ((string)(this["ServiceIntegration_wsArmProxy_IAPO2_ARM_READERservice"]));
            }
        }
    }
}
